import json
from datetime import datetime
from decimal import Decimal
from typing import Any
from zoneinfo import ZoneInfo

from psycopg import Connection

from openslides_backend.models.models import Meeting
from openslides_backend.services.postgresql.db_connection_handling import (
    get_new_os_conn,
)
from openslides_backend.shared.patterns import strip_reserved_fields

standard_data: dict[str, dict[int, Any]] = {
    "user": {
        1: {
            "id": 1,
            "username": "data",
            "default_vote_weight": "42.000000",
            "is_demo_user": True,
            "last_login": "2042/11/19 9:53:20",
        },
        2: {
            "id": 2,
            "username": "daren",
            "first_name": "daren",
            "last_name": "nerad",
            "last_login": "2012/05/31",
            "default_vote_weight": "23.000000",
            "is_demo_user": False,
        },
        3: {
            "id": 3,
            "username": "3",
            "first_name": "nerad",
            "default_vote_weight": "81.000000",
            "is_demo_user": True,
        },
    },
    "committee": {
        1: {
            "name": "23",
        },
        2: {
            "name": "42",
        },
    },
}

standard_responses: dict[str, dict[int, dict[str, Any]]] = {
    "user": {
        1: {
            "id": 1,
            "username": "data",
            "member_number": None,
            "saml_id": None,
            "pronoun": None,
            "title": None,
            "first_name": None,
            "last_name": None,
            "is_active": True,
            "is_physical_person": True,
            "password": None,
            "default_password": None,
            "can_change_own_password": True,
            "gender_id": None,
            "history_entry_ids": None,
            "history_position_ids": None,
            "external": None,
            "home_committee_id": None,
            "email": None,
            "default_vote_weight": Decimal("42"),
            "last_email_sent": None,
            "is_demo_user": True,
            "last_login": datetime(2042, 11, 19, 9, 53, 20, tzinfo=ZoneInfo("UTC")),
            "organization_management_level": None,
            "meeting_ids": None,
            "is_present_in_meeting_ids": None,
            "meeting_user_ids": None,
            "option_ids": None,
            "poll_candidate_ids": None,
            "poll_voted_ids": None,
            "vote_ids": None,
            "committee_ids": None,
            "committee_management_ids": None,
            "delegated_vote_ids": None,
            "organization_id": 1,
        },
        2: {
            "id": 2,
            "username": "daren",
            "member_number": None,
            "saml_id": None,
            "pronoun": None,
            "title": None,
            "first_name": "daren",
            "last_name": "nerad",
            "is_active": True,
            "is_physical_person": True,
            "password": None,
            "default_password": None,
            "can_change_own_password": True,
            "gender_id": None,
            "history_entry_ids": None,
            "history_position_ids": None,
            "external": None,
            "home_committee_id": None,
            "email": None,
            "default_vote_weight": Decimal("23"),
            "last_email_sent": None,
            "is_demo_user": False,
            "last_login": datetime(2012, 5, 31, 0, 0, tzinfo=ZoneInfo("UTC")),
            "organization_management_level": None,
            "meeting_ids": None,
            "is_present_in_meeting_ids": None,
            "meeting_user_ids": None,
            "option_ids": None,
            "poll_candidate_ids": None,
            "poll_voted_ids": None,
            "vote_ids": None,
            "committee_ids": None,
            "committee_management_ids": None,
            "delegated_vote_ids": None,
            "organization_id": 1,
        },
        3: {
            "id": 3,
            "username": "3",
            "member_number": None,
            "saml_id": None,
            "pronoun": None,
            "title": None,
            "first_name": "nerad",
            "last_name": None,
            "is_active": True,
            "is_physical_person": True,
            "password": None,
            "default_password": None,
            "can_change_own_password": True,
            "gender_id": None,
            "history_entry_ids": None,
            "history_position_ids": None,
            "external": None,
            "home_committee_id": None,
            "email": None,
            "default_vote_weight": Decimal("81"),
            "last_email_sent": None,
            "is_demo_user": True,
            "last_login": None,
            "organization_management_level": None,
            "meeting_ids": None,
            "is_present_in_meeting_ids": None,
            "meeting_user_ids": None,
            "option_ids": None,
            "poll_candidate_ids": None,
            "poll_voted_ids": None,
            "vote_ids": None,
            "committee_ids": None,
            "committee_management_ids": None,
            "delegated_vote_ids": None,
            "organization_id": 1,
        },
    },
    "committee": {
        1: {
            "all_child_ids": None,
            "all_parent_ids": None,
            "child_ids": None,
            "id": 1,
            "name": "23",
            "description": None,
            "external_id": None,
            "default_meeting_id": None,
            "forward_to_committee_ids": None,
            "manager_ids": None,
            "meeting_ids": None,
            "native_user_ids": None,
            "organization_tag_ids": None,
            "parent_id": None,
            "receive_forwardings_from_committee_ids": None,
            "user_ids": None,
            "organization_id": 1,
        },
        2: {
            "all_child_ids": None,
            "all_parent_ids": None,
            "child_ids": None,
            "id": 2,
            "name": "42",
            "description": None,
            "external_id": None,
            "default_meeting_id": None,
            "forward_to_committee_ids": None,
            "manager_ids": None,
            "meeting_ids": None,
            "native_user_ids": None,
            "organization_id": 1,
            "organization_tag_ids": None,
            "parent_id": None,
            "receive_forwardings_from_committee_ids": None,
            "user_ids": None,
        },
    },
}


meeting_data: dict[str, dict[int, Any]] = {
    "group": {
        1: {
            "name": "default",
            "meeting_id": 1,
            "permissions": [
                "agenda_item.can_see_internal",
                "assignment.can_see",
                "list_of_speakers.can_see",
                "mediafile.can_see",
                "meeting.can_see_frontpage",
                "motion.can_see",
                "projector.can_see",
                "user.can_see",
            ],
        },
        2: {
            "name": "staff",
            "meeting_id": 1,
            "permissions": [
                "agenda_item.can_manage",
                "assignment.can_manage",
                "assignment.can_manage_polls",
                "assignment.can_nominate_self",
                "list_of_speakers.can_be_speaker",
                "list_of_speakers.can_manage",
                "mediafile.can_manage",
                "meeting.can_see_frontpage",
                "meeting.can_see_history",
                "motion.can_manage",
                "motion.can_manage_polls",
                "poll.can_manage",
                "projector.can_manage",
                "tag.can_manage",
                "user.can_manage",
            ],
        },
    },
    "projector": {
        1: {
            "name": "first projector",
            "meeting_id": 1,
            **{field: 1 for field in Meeting.reverse_default_projectors()},
        }
    },
    "motion_state": {
        1: {"weight": 1, "name": "first state", "meeting_id": 1, "workflow_id": 1}
    },
    "motion_workflow": {
        1: {"name": "first workflow", "meeting_id": 1, "first_state_id": 1}
    },
    "meeting": {
        1: {
            "committee_id": 1,
            "motions_default_workflow_id": 1,
            "motions_default_amendment_workflow_id": 1,
            "reference_projector_id": 1,
            "default_group_id": 1,
            "admin_group_id": 1,
        },
    },
}

meeting_responses: dict[str, dict[int, dict[str, Any]]] = {
    "group": {
        1: {
            "admin_group_for_meeting_id": 1,
            "anonymous_group_for_meeting_id": None,
            "default_group_for_meeting_id": 1,
            "external_id": None,
            "id": 1,
            "meeting_id": 1,
            "meeting_mediafile_access_group_ids": None,
            "meeting_mediafile_inherited_access_group_ids": None,
            "meeting_user_ids": None,
            "name": "default",
            "permissions": [
                "agenda_item.can_see_internal",
                "assignment.can_see",
                "list_of_speakers.can_see",
                "mediafile.can_see",
                "meeting.can_see_frontpage",
                "motion.can_see",
                "projector.can_see",
                "user.can_see",
            ],
            "poll_ids": None,
            "read_chat_group_ids": None,
            "read_comment_section_ids": None,
            "used_as_assignment_poll_default_id": None,
            "used_as_motion_poll_default_id": None,
            "used_as_poll_default_id": None,
            "used_as_topic_poll_default_id": None,
            "weight": None,
            "write_chat_group_ids": None,
            "write_comment_section_ids": None,
        },
        2: {
            "admin_group_for_meeting_id": None,
            "anonymous_group_for_meeting_id": None,
            "default_group_for_meeting_id": None,
            "external_id": None,
            "id": 2,
            "meeting_id": 1,
            "meeting_mediafile_access_group_ids": None,
            "meeting_mediafile_inherited_access_group_ids": None,
            "meeting_user_ids": None,
            "name": "staff",
            "permissions": [
                "agenda_item.can_manage",
                "assignment.can_manage",
                "assignment.can_manage_polls",
                "assignment.can_nominate_self",
                "list_of_speakers.can_be_speaker",
                "list_of_speakers.can_manage",
                "mediafile.can_manage",
                "meeting.can_see_frontpage",
                "meeting.can_see_history",
                "motion.can_manage",
                "motion.can_manage_polls",
                "poll.can_manage",
                "projector.can_manage",
                "tag.can_manage",
                "user.can_manage",
            ],
            "poll_ids": None,
            "read_chat_group_ids": None,
            "read_comment_section_ids": None,
            "used_as_assignment_poll_default_id": None,
            "used_as_motion_poll_default_id": None,
            "used_as_poll_default_id": None,
            "used_as_topic_poll_default_id": None,
            "weight": None,
            "write_chat_group_ids": None,
            "write_comment_section_ids": None,
        },
    },
    "projector": {
        1: {
            "aspect_ratio_denominator": 9,
            "aspect_ratio_numerator": 16,
            "background_color": "#ffffff",
            "chyron_background_color": "#317796",
            "chyron_background_color_2": "#134768",
            "chyron_font_color": "#ffffff",
            "chyron_font_color_2": "#ffffff",
            "color": "#000000",
            "current_projection_ids": None,
            "header_background_color": "#317796",
            "header_font_color": "#f5f5f5",
            "header_h1_color": "#317796",
            "history_projection_ids": None,
            "id": 1,
            "is_internal": False,
            "meeting_id": 1,
            "name": "first projector",
            "preview_projection_ids": None,
            "scale": 0,
            "scroll": 0,
            "sequential_number": 1,
            "show_clock": True,
            "show_header_footer": True,
            "show_logo": True,
            "show_title": True,
            "used_as_default_projector_for_agenda_item_list_in_meeting_id": 1,
            "used_as_default_projector_for_amendment_in_meeting_id": 1,
            "used_as_default_projector_for_assignment_in_meeting_id": 1,
            "used_as_default_projector_for_assignment_poll_in_meeting_id": 1,
            "used_as_default_projector_for_countdown_in_meeting_id": 1,
            "used_as_default_projector_for_current_los_in_meeting_id": 1,
            "used_as_default_projector_for_list_of_speakers_in_meeting_id": 1,
            "used_as_default_projector_for_mediafile_in_meeting_id": 1,
            "used_as_default_projector_for_message_in_meeting_id": 1,
            "used_as_default_projector_for_motion_block_in_meeting_id": 1,
            "used_as_default_projector_for_motion_in_meeting_id": 1,
            "used_as_default_projector_for_motion_poll_in_meeting_id": 1,
            "used_as_default_projector_for_poll_in_meeting_id": 1,
            "used_as_default_projector_for_topic_in_meeting_id": 1,
            "used_as_reference_projector_meeting_id": 1,
            "width": 1200,
        },
    },
    "motion_state": {
        1: {
            "allow_amendment_forwarding": None,
            "allow_create_poll": False,
            "allow_motion_forwarding": False,
            "allow_submitter_edit": False,
            "allow_support": False,
            "css_class": "lightblue",
            "first_state_of_workflow_id": 1,
            "id": 1,
            "is_internal": None,
            "meeting_id": 1,
            "merge_amendment_into_final": "undefined",
            "motion_ids": None,
            "motion_recommendation_ids": None,
            "name": "first state",
            "next_state_ids": None,
            "previous_state_ids": None,
            "recommendation_label": None,
            "restrictions": [],
            "set_number": True,
            "set_workflow_timestamp": False,
            "show_recommendation_extension_field": False,
            "show_state_extension_field": False,
            "state_button_label": None,
            "submitter_withdraw_back_ids": None,
            "submitter_withdraw_state_id": None,
            "weight": 1,
            "workflow_id": 1,
        },
    },
    "motion_workflow": {
        1: {
            "default_amendment_workflow_meeting_id": 1,
            "default_workflow_meeting_id": 1,
            "first_state_id": 1,
            "id": 1,
            "meeting_id": 1,
            "name": "first workflow",
            "sequential_number": 1,
            "state_ids": [
                1,
            ],
        }
    },
    "meeting": {
        1: {
            "admin_group_id": 1,
            "agenda_enable_numbering": True,
            "agenda_item_creation": "default_no",
            "agenda_item_ids": None,
            "agenda_new_items_default_visibility": "internal",
            "agenda_number_prefix": None,
            "agenda_numeral_system": "arabic",
            "agenda_show_internal_items_on_projector": False,
            "agenda_show_subtitles": False,
            "agenda_show_topic_navigation_on_detail_view": False,
            "all_projection_ids": None,
            "anonymous_group_id": None,
            "applause_enable": False,
            "applause_max_amount": 0,
            "applause_min_amount": 1,
            "applause_particle_image_url": None,
            "applause_show_level": False,
            "applause_timeout": 5,
            "applause_type": "applause-type-bar",
            "assignment_candidate_ids": None,
            "assignment_ids": None,
            "assignment_poll_add_candidates_to_list_of_speakers": False,
            "assignment_poll_ballot_paper_number": 8,
            "assignment_poll_ballot_paper_selection": "CUSTOM_NUMBER",
            "assignment_poll_default_backend": "fast",
            "assignment_poll_default_group_ids": None,
            "assignment_poll_default_method": "Y",
            "assignment_poll_default_onehundred_percent_base": "valid",
            "assignment_poll_default_type": "pseudoanonymous",
            "assignment_poll_enable_max_votes_per_option": False,
            "assignment_poll_sort_poll_result_by_votes": True,
            "assignments_export_preamble": None,
            "assignments_export_title": "Elections",
            "chat_group_ids": None,
            "chat_message_ids": None,
            "committee_id": 1,
            "conference_auto_connect": False,
            "conference_auto_connect_next_speakers": 0,
            "conference_enable_helpdesk": False,
            "conference_los_restriction": True,
            "conference_open_microphone": False,
            "conference_open_video": False,
            "conference_show": False,
            "conference_stream_poster_url": None,
            "conference_stream_url": None,
            "custom_translations": None,
            "default_group_id": 1,
            "default_meeting_for_committee_id": None,
            "default_projector_agenda_item_list_ids": [
                1,
            ],
            "default_projector_amendment_ids": [
                1,
            ],
            "default_projector_assignment_ids": [
                1,
            ],
            "default_projector_assignment_poll_ids": [
                1,
            ],
            "default_projector_countdown_ids": [
                1,
            ],
            "default_projector_current_los_ids": [
                1,
            ],
            "default_projector_list_of_speakers_ids": [
                1,
            ],
            "default_projector_mediafile_ids": [
                1,
            ],
            "default_projector_message_ids": [
                1,
            ],
            "default_projector_motion_block_ids": [
                1,
            ],
            "default_projector_motion_ids": [
                1,
            ],
            "default_projector_motion_poll_ids": [
                1,
            ],
            "default_projector_poll_ids": [
                1,
            ],
            "default_projector_topic_ids": [
                1,
            ],
            "description": None,
            "enable_anonymous": False,
            "end_time": None,
            "export_csv_encoding": "utf-8",
            "export_csv_separator": ";",
            "export_pdf_fontsize": 10,
            "export_pdf_line_height": 1.25,
            "export_pdf_page_margin_bottom": 20,
            "export_pdf_page_margin_left": 20,
            "export_pdf_page_margin_right": 20,
            "export_pdf_page_margin_top": 25,
            "export_pdf_pagenumber_alignment": "center",
            "export_pdf_pagesize": "A4",
            "external_id": None,
            "font_bold_id": None,
            "font_bold_italic_id": None,
            "font_chyron_speaker_name_id": None,
            "font_italic_id": None,
            "font_monospace_id": None,
            "font_projector_h1_id": None,
            "font_projector_h2_id": None,
            "font_regular_id": None,
            "forwarded_motion_ids": None,
            "group_ids": [
                1,
                2,
            ],
            "id": 1,
            "imported_at": None,
            "is_active_in_organization_id": None,
            "is_archived_in_organization_id": None,
            "jitsi_domain": None,
            "jitsi_room_name": None,
            "jitsi_room_password": None,
            "language": "en",
            "list_of_speakers_allow_multiple_speakers": False,
            "list_of_speakers_amount_last_on_projector": 0,
            "list_of_speakers_amount_next_on_projector": -1,
            "list_of_speakers_can_create_point_of_order_for_others": False,
            "list_of_speakers_can_set_contribution_self": False,
            "list_of_speakers_closing_disables_point_of_order": False,
            "list_of_speakers_countdown_id": None,
            "list_of_speakers_couple_countdown": True,
            "list_of_speakers_default_structure_level_time": None,
            "list_of_speakers_enable_interposed_question": None,
            "list_of_speakers_enable_point_of_order_categories": False,
            "list_of_speakers_enable_point_of_order_speakers": True,
            "list_of_speakers_enable_pro_contra_speech": False,
            "list_of_speakers_hide_contribution_count": False,
            "list_of_speakers_ids": None,
            "list_of_speakers_initially_closed": False,
            "list_of_speakers_intervention_time": None,
            "list_of_speakers_present_users_only": False,
            "list_of_speakers_show_amount_of_speakers_on_slide": True,
            "list_of_speakers_show_first_contribution": False,
            "list_of_speakers_speaker_note_for_everyone": True,
            "location": None,
            "locked_from_inside": None,
            "logo_pdf_ballot_paper_id": None,
            "logo_pdf_footer_l_id": None,
            "logo_pdf_footer_r_id": None,
            "logo_pdf_header_l_id": None,
            "logo_pdf_header_r_id": None,
            "logo_projector_header_id": None,
            "logo_projector_main_id": None,
            "logo_web_header_id": None,
            "mediafile_ids": None,
            "meeting_mediafile_ids": None,
            "meeting_user_ids": None,
            "motion_block_ids": None,
            "motion_category_ids": None,
            "motion_change_recommendation_ids": None,
            "motion_comment_ids": None,
            "motion_comment_section_ids": None,
            "motion_editor_ids": None,
            "motion_ids": None,
            "motion_poll_ballot_paper_number": 8,
            "motion_poll_ballot_paper_selection": "CUSTOM_NUMBER",
            "motion_poll_default_backend": "fast",
            "motion_poll_default_group_ids": None,
            "motion_poll_default_method": "YNA",
            "motion_poll_default_onehundred_percent_base": "YNA",
            "motion_poll_default_type": "pseudoanonymous",
            "motion_poll_projection_max_columns": 6,
            "motion_poll_projection_name_order_first": "last_name",
            "motion_state_ids": [
                1,
            ],
            "motion_submitter_ids": None,
            "motion_supporter_ids": None,
            "motion_workflow_ids": [
                1,
            ],
            "motion_working_group_speaker_ids": None,
            "motions_amendments_enabled": True,
            "motions_amendments_in_main_list": True,
            "motions_amendments_multiple_paragraphs": True,
            "motions_amendments_of_amendments": False,
            "motions_amendments_prefix": "-Ä",
            "motions_amendments_text_mode": "paragraph",
            "motions_block_slide_columns": None,
            "motions_create_enable_additional_submitter_text": None,
            "motions_default_amendment_workflow_id": 1,
            "motions_default_line_numbering": "outside",
            "motions_default_sorting": "number",
            "motions_default_workflow_id": 1,
            "motions_enable_editor": None,
            "motions_enable_origin_motion_display": False,
            "motions_enable_reason_on_projector": False,
            "motions_enable_recommendation_on_projector": True,
            "motions_enable_restricted_editor_for_manager": None,
            "motions_enable_restricted_editor_for_non_manager": None,
            "motions_enable_sidebox_on_projector": False,
            "motions_enable_text_on_projector": True,
            "motions_enable_working_group_speaker": None,
            "motions_export_follow_recommendation": False,
            "motions_export_preamble": None,
            "motions_export_submitter_recommendation": True,
            "motions_export_title": "Motions",
            "motions_hide_metadata_background": False,
            "motions_line_length": 85,
            "motions_number_min_digits": 2,
            "motions_number_type": "per_category",
            "motions_number_with_blank": False,
            "motions_origin_motion_toggle_default": False,
            "motions_preamble": "The assembly may decide:",
            "motions_reason_required": False,
            "motions_recommendation_text_mode": "diff",
            "motions_recommendations_by": None,
            "motions_show_referring_motions": True,
            "motions_show_sequential_number": True,
            "motions_supporters_min_amount": 0,
            "name": "OpenSlides",
            "option_ids": None,
            "organization_tag_ids": None,
            "personal_note_ids": None,
            "point_of_order_category_ids": None,
            "poll_ballot_paper_number": None,
            "poll_ballot_paper_selection": None,
            "poll_candidate_ids": None,
            "poll_candidate_list_ids": None,
            "poll_countdown_id": None,
            "poll_couple_countdown": True,
            "poll_default_backend": "fast",
            "poll_default_group_ids": None,
            "poll_default_live_voting_enabled": False,
            "poll_default_method": None,
            "poll_default_onehundred_percent_base": "YNA",
            "poll_default_type": "analog",
            "poll_ids": None,
            "poll_sort_poll_result_by_votes": None,
            "present_user_ids": None,
            "projection_ids": None,
            "projector_countdown_default_time": 60,
            "projector_countdown_ids": None,
            "projector_countdown_warning_time": 0,
            "projector_ids": [
                1,
            ],
            "projector_message_ids": None,
            "reference_projector_id": 1,
            "relevant_history_entry_ids": None,
            "speaker_ids": None,
            "start_time": None,
            "structure_level_ids": None,
            "structure_level_list_of_speakers_ids": None,
            "tag_ids": None,
            "template_for_organization_id": None,
            "topic_ids": None,
            "topic_poll_default_group_ids": None,
            "user_ids": None,
            "users_allow_self_set_present": True,
            "users_email_body": "Dear {name},\n"
            "\n"
            "this is your personal OpenSlides login:\n"
            "\n"
            "{url}\n"
            "Username: {username}\n"
            "Password: {password}\n"
            "\n"
            "\n"
            "This email was generated automatically.",
            "users_email_replyto": None,
            "users_email_sender": "OpenSlides",
            "users_email_subject": "OpenSlides access data",
            "users_enable_presence_view": False,
            "users_enable_vote_delegations": None,
            "users_enable_vote_weight": False,
            "users_forbid_delegator_as_submitter": None,
            "users_forbid_delegator_as_supporter": None,
            "users_forbid_delegator_in_list_of_speakers": None,
            "users_forbid_delegator_to_vote": None,
            "users_pdf_welcometext": "[Place for your welcome and help text.]",
            "users_pdf_welcometitle": "Welcome to OpenSlides",
            "users_pdf_wlan_encryption": "WPA",
            "users_pdf_wlan_password": None,
            "users_pdf_wlan_ssid": None,
            "vote_ids": None,
            "welcome_text": "Space for your welcome text.",
            "welcome_title": "Welcome to OpenSlides",
        },
    },
}


def setup_data(connection: Connection, data: dict[str, dict[int, Any]]) -> None:
    with connection.cursor() as cursor:
        for collection, models in data.items():
            for model in models.values():
                model_data = json.loads(json.dumps(model))
                strip_reserved_fields(model_data)
                cursor.execute(
                    f"INSERT INTO {collection}_t ({', '.join(key for key in model_data.keys())}) VALUES ({', '.join('%s' for i in range(len(model_data)))})",
                    [val for val in model_data.values()],
                )
    connection.commit()


def insert_into_intermediate_table(
    table: str, columns: list[str], data: list[tuple[int, int]]
) -> None:
    with get_new_os_conn() as connection:
        with connection.cursor() as cursor:
            for values in data:
                cursor.execute(
                    f"INSERT INTO {table} ({', '.join(columns)}) VALUES {values}"
                )
