from collections.abc import Iterable
from typing import Any

from openslides_backend.action.actions.motion.create import MotionCreate
from openslides_backend.action.ddaction import DDAction
from openslides_backend.action.generics.create import CreateAction
from openslides_backend.action.util.actions_map import actions_map
from openslides_backend.action.util.register import register_action
from openslides_backend.action.util.typing import ActionData, ActionResults
from openslides_backend.models import fields
from openslides_backend.models.base import model_registry
from openslides_backend.permissions.permissions import Permissions
from openslides_backend.services.postgresql.db_connection_handling import (
    get_new_os_conn,
)
from openslides_backend.shared.exceptions import ActionException
from openslides_backend.shared.interfaces.event import Event, EventType
from openslides_backend.shared.patterns import fqid_from_collection_and_id
from openslides_backend.shared.typing import HistoryInformation
from tests.patch_model_registry_helper import (
    FakeModel,
    PatchModelRegistryMixin,
    fake_registry,
)
from tests.util import Response

from .base import BaseActionTestCase

collection_mai = "fake_model_mai"


def create_table_view() -> None:
    sql = f"""
    CREATE TABLE IF NOT EXISTS {collection_mai}_t (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        meeting_id integer,
        motion_id integer
    );

    DROP VIEW IF EXISTS "{collection_mai}";
    CREATE VIEW "{collection_mai}" AS SELECT * FROM {collection_mai}_t;
    """
    with get_new_os_conn() as conn:
        with conn.cursor() as curs:
            curs.execute(sql)


class FakeModelMai(FakeModel):
    collection = "fake_model_mai"
    verbose_name = "fake model for permissions"
    id = fields.IntegerField()
    meeting_id = fields.IntegerField()
    motion_id = fields.IntegerField()


@register_action("fake_model_mai.legacy_create")
class LegacyFakeModelMaiCreate(CreateAction):
    model = FakeModelMai()
    schema = {}  # type: ignore
    permission = Permissions.Motion.CAN_CREATE

    def create_events(self, instance: dict[str, Any]) -> Iterable[Event]:
        yield from super().create_events(instance)
        yield self.build_event(
            EventType.Update,
            fqid_from_collection_and_id("motion", instance["motion_id"]),
            {"id": instance["motion_id"]},
        )

    def update_instance(self, instance: dict[str, Any]) -> dict[str, Any]:
        if instance.get("fail"):
            raise ActionException("Cannot create fake_model_mai.")
        if "motion_id" not in instance:
            result = self.execute_other_action(
                MotionCreate,
                [
                    {
                        "meeting_id": instance["meeting_id"],
                        "title": instance.pop("motion_title"),
                        "text": instance.pop("motion_text"),
                    }
                ],
            )
            assert result
            assert result[0]
            instance["motion_id"] = result[0]["id"]
        return super().update_instance(instance)

    def get_history_information(self) -> HistoryInformation | None:
        motion_id_to_fm_amount: dict[int, int] = {}
        for instance in self.instances:
            if (motion_id := instance["motion_id"]) not in motion_id_to_fm_amount:
                motion_id_to_fm_amount[motion_id] = 1
            else:
                motion_id_to_fm_amount[motion_id] += 1
        return {
            f"motion/{motion_id}": [
                "Added 1 fake model." if amount == 1 else f"Added {amount} fake models."
            ]
            for motion_id, amount in motion_id_to_fm_amount.items()
        }


@register_action("fake_model_mai.create")
class FakeModelPCreate(DDAction):
    model = FakeModelMai()
    schema = {}  # type: ignore
    permission = Permissions.Motion.CAN_CREATE

    def write_instances(self, action_data: ActionData) -> ActionResults | None:
        instances = list(action_data)
        return_data: ActionResults = []
        motion_id_to_fm_amount: dict[int, int] = {}
        for instance in instances:
            if instance.get("fail"):
                raise ActionException("Cannot create fake_model_mai.")
            if "motion_id" not in instance:
                result = self.execute_other_action(
                    MotionCreate,
                    [
                        {
                            "meeting_id": instance["meeting_id"],
                            "title": instance.pop("motion_title"),
                            "text": instance.pop("motion_text"),
                        }
                    ],
                )
                assert result
                assert result[0]
                instance["motion_id"] = motion_id = result[0]["id"]
            else:
                motion_id = instance["motion_id"]
            if motion_id not in motion_id_to_fm_amount:
                motion_id_to_fm_amount[motion_id] = 1
            else:
                motion_id_to_fm_amount[motion_id] += 1
            return_data.extend(
                list(
                    self.database.insert_models(
                        self.model.collection,
                        [instance],
                        list({field for field in instance}),
                    )
                )
            )
        self.write_history_information(
            {
                f"motion/{motion_id}": [
                    (
                        "Added 1 fake model."
                        if amount == 1
                        else f"Added {amount} fake models."
                    )
                ]
                for motion_id, amount in motion_id_to_fm_amount.items()
            }
        )
        return return_data


class TestMultiActionInterplayFakeActions(PatchModelRegistryMixin, BaseActionTestCase):
    """
    Tests the interaction between old-style and new-style actions,
    specifically when they are requested together.
    Uses fake models to also be able to check the history.
    Can't test internal requests here bc they don't mesh with history (bc no valid user_id).
    """

    fake_model_registry = model_registry | fake_registry
    init_with_login = True
    create_action_name = "fake_model_p.create"

    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        create_table_view()

    @classmethod
    def tearDownClass(cls) -> None:
        super().tearDownClass()
        with get_new_os_conn() as conn:
            with conn.cursor() as curs:
                curs.execute(f"DROP TABLE {collection_mai}_t CASCADE;")

    def setUp(self) -> None:
        super().setUp()
        self.create_meeting()
        self.create_motion(1)
        self.test_payloads: list[list[dict[str, Any]]] = [
            [
                {
                    "meeting_id": 1,
                    "motion_title": "Motion 2",
                    "motion_text": "This motion is new",
                },
                {"meeting_id": 1, "motion_id": 1},
            ],
            [
                {"meeting_id": 1, "motion_id": 1},
                {
                    "meeting_id": 1,
                    "motion_title": "Motion 3",
                    "motion_text": "This motion is new too.",
                },
            ],
            [
                {
                    "meeting_id": 1,
                    "motion_title": "Motion 4",
                    "motion_text": "Another new motion.",
                },
                {"meeting_id": 1, "motion_id": 1},
            ],
            [{"meeting_id": 1, "motion_id": 1}, {"meeting_id": 1, "motion_id": 1}],
            [{"meeting_id": 1, "motion_id": 1}, {"meeting_id": 1, "motion_id": 1}],
        ]
        self.expect_data: dict[str, dict[str, Any] | None] = {
            "motion/2": {
                "meeting_id": 1,
                "title": "Motion 2",
                "text": "This motion is new",
            },
            "motion/3": {
                "meeting_id": 1,
                "title": "Motion 3",
                "text": "This motion is new too.",
            },
            "motion/4": {
                "meeting_id": 1,
                "title": "Motion 4",
                "text": "Another new motion.",
            },
            "motion/5": None,
            "fake_model_mai/1": {"meeting_id": 1, "motion_id": 2},
            "fake_model_mai/2": {"meeting_id": 1, "motion_id": 1},
            "fake_model_mai/3": {"meeting_id": 1, "motion_id": 1},
            "fake_model_mai/4": {"meeting_id": 1, "motion_id": 3},
            "fake_model_mai/5": {"meeting_id": 1, "motion_id": 4},
            "fake_model_mai/6": {"meeting_id": 1, "motion_id": 1},
            "fake_model_mai/7": {"meeting_id": 1, "motion_id": 1},
            "fake_model_mai/8": {"meeting_id": 1, "motion_id": 1},
            "fake_model_mai/9": {"meeting_id": 1, "motion_id": 1},
            "fake_model_mai/10": {"meeting_id": 1, "motion_id": 1},
            "fake_model_mai/11": None,
        }
        self.expected_history_entries_per_action: list[dict[str, list[str]]] = [
            {
                "motion/1": ["Added 1 fake model."],
                "motion/2": ["Motion created", "Added 1 fake model."],
            },
            {
                "motion/1": ["Added 1 fake model."],
                "motion/3": ["Motion created", "Added 1 fake model."],
            },
            {
                "motion/1": ["Added 1 fake model."],
                "motion/4": ["Motion created", "Added 1 fake model."],
            },
            {
                "motion/1": ["Added 2 fake models."],
            },
            {
                "motion/1": ["Added 2 fake models."],
            },
        ]

    def tearDown(self) -> None:
        super().tearDown()
        with self.connection.cursor() as curs:
            curs.execute(f"""
                TRUNCATE TABLE {collection_mai}_t RESTART IDENTITY;
                """)

    def assert_results(self, response: Response) -> None:
        self.assert_status_code(response, 200)
        for fqid, expected in self.expect_data.items():
            if expected:
                self.assert_model_exists(fqid, expected)
            else:
                self.assert_model_not_exists(fqid)
        next_entry_id = 1
        for pos_id, expect_entries in enumerate(
            self.expected_history_entries_per_action, 1
        ):
            entry_ids = list(range(next_entry_id, next_entry_id + len(expect_entries)))
            next_entry_id += len(expect_entries)
            self.assert_model_exists(
                f"history_position/{pos_id}", {"user_id": 1, "entry_ids": entry_ids}
            )
            entries = [
                self.assert_model_exists(
                    f"history_entry/{id_}", {"position_id": pos_id}
                )
                for id_ in entry_ids
            ]
            motion_fqid_to_entry = {
                entry["original_model_id"]: entry for entry in entries
            }
            for expect_fqid, expect_string_list in expect_entries.items():
                assert expect_fqid in motion_fqid_to_entry
                entry = motion_fqid_to_entry[expect_fqid]
                assert entry.get("model_id") == expect_fqid
                assert entry.get("entries") == expect_string_list
        self.assert_model_not_exists("history_position/6")
        self.assert_model_not_exists(f"history_entry/{next_entry_id}")

    def test_parse_actions_normal_mixed(self) -> None:
        order = [True, False, True, False, True]
        response = self.request_json(
            [
                {
                    "action": (
                        "fake_model_mai.legacy_create"
                        if is_legacy
                        else "fake_model_mai.create"
                    ),
                    "data": payloads,
                }
                for is_legacy, payloads in zip(order, self.test_payloads)
            ]
        )
        self.assert_results(response)

    def test_parse_actions_normal_all_legacy(self) -> None:
        response = self.request_json(
            [
                {
                    "action": "fake_model_mai.legacy_create",
                    "data": payloads,
                }
                for payloads in self.test_payloads
            ]
        )
        self.assert_results(response)

    def test_parse_actions_normal_all_new_style(self) -> None:
        response = self.request_json(
            [
                {
                    "action": "fake_model_mai.create",
                    "data": payloads,
                }
                for payloads in self.test_payloads
            ]
        )
        self.assert_results(response)

    def test_parse_actions_non_atomic(self) -> None:
        order = [True, False, True, False, True]
        response = self.request_json(
            [
                {
                    "action": (
                        "fake_model_mai.legacy_create"
                        if is_legacy
                        else "fake_model_mai.create"
                    ),
                    "data": payloads,
                }
                for is_legacy, payloads in zip(order, self.test_payloads)
            ],
            atomic=False,
        )
        self.assert_results(response)

    def fail_test(
        self, fail_at: int, are_actions_legacy: tuple[bool, bool, bool, bool, bool]
    ) -> None:
        if fail_at >= 5:
            raise Exception("Test broken: fail_at too big.")
        response = self.request_json(
            [
                {
                    "action": (
                        "fake_model_mai.legacy_create"
                        if is_legacy
                        else "fake_model_mai.create"
                    ),
                    "data": (
                        [payloads[0] | {"fail": True}, *payloads[1:]]
                        if i == fail_at
                        else payloads
                    ),
                }
                for i, (is_legacy, payloads) in enumerate(
                    zip(are_actions_legacy, self.test_payloads)
                )
            ]
        )
        self.assert_status_code(response, 400)
        assert response.json["message"] == "Cannot create fake_model_mai."
        for fqid in self.expect_data:
            self.assert_model_not_exists(fqid)
        next_entry_id = 1
        for pos_id, entries in enumerate(self.expected_history_entries_per_action, 1):
            self.assert_model_not_exists(f"history_position/{pos_id}")
            for _ in entries:
                self.assert_model_not_exists(f"history_entry/{next_entry_id}")
                next_entry_id += 1

    def test_parse_actions_legacy_fails_at_start(self) -> None:
        order = (True, False, True, False, True)
        self.fail_test(0, order)

    def test_parse_actions_new_style_fails_at_start(self) -> None:
        order = (False, True, False, True, False)
        self.fail_test(0, order)

    def test_parse_actions_legacy_fails_in_middle(self) -> None:
        order = (True, False, True, False, True)
        self.fail_test(2, order)

    def test_parse_actions_new_style_fails_in_middle(self) -> None:
        order = (False, True, False, True, False)
        self.fail_test(2, order)

    def test_parse_actions_legacy_fails_at_end(self) -> None:
        order = (True, False, True, False, True)
        self.fail_test(4, order)

    def test_parse_actions_new_style_fails_at_end(self) -> None:
        order = (False, True, False, True, False)
        self.fail_test(4, order)


class TestMultiActionInterplayRealActions(BaseActionTestCase):
    """
    Tests the interaction between old-style and new-style actions,
    specifically when they are requested together.

    This test is specifically to ensure that multiple styles of action are tested, along with the internal route.
    """

    # list of action_name, payloads, return_object, expected_results tuples
    # to be tested together in that order.
    case_actions: list[
        list[
            tuple[
                str,
                list[dict[str, Any]],
                ActionResults | None,
                dict[str, dict[str, Any] | None],
            ]
        ]
    ] = [
        [
            (
                "organization_tag.create",
                [
                    {"name": "Never", "color": "#123456", "organization_id": 1},
                    {"name": "gonna", "color": "#789abc", "organization_id": 1},
                ],
                [{"id": id_} for id_ in [1, 2]],
                {
                    "organization_tag/1": {
                        "name": "Never",
                        "color": "#123456",
                        "organization_id": 1,
                    },
                    "organization_tag/2": {
                        "name": "gonna",
                        "color": "#789abc",
                        "organization_id": 1,
                    },
                },
            ),  # legacy for now
            (
                "motion_workflow.create",
                [
                    {"name": "give", "meeting_id": 1},
                    {"name": "you", "meeting_id": 1},
                    {"name": "up.", "meeting_id": 1},
                ],
                [{"id": id_, "sequential_number": id_} for id_ in [2, 3, 4]],
                {
                    "motion_workflow/2": {"name": "give", "meeting_id": 1},
                    "motion_workflow/3": {"name": "you", "meeting_id": 1},
                    "motion_workflow/4": {"name": "up.", "meeting_id": 1},
                },
            ),
            (
                "user.update",
                [{"id": 1, "meeting_id": 1, "group_ids": [2]}],
                [None],
                {"meeting_user/1": {"user_id": 1, "meeting_id": 1, "group_ids": [2]}},
            ),  # legacy for now
            (
                "theme.create",
                [
                    {
                        "name": "Never",
                        "primary_500": "#aaaaaa",
                        "accent_500": "#bbbbbb",
                        "warn_500": "#cccccc",
                    },
                    {
                        "name": "gonna",
                        "primary_500": "#dddddd",
                        "accent_500": "#eeeeee",
                        "warn_500": "#ffffff",
                    },
                ],
                [{"id": id_} for id_ in [2, 3]],
                {
                    "theme/2": {
                        "name": "Never",
                        "primary_500": "#aaaaaa",
                        "accent_500": "#bbbbbb",
                        "warn_500": "#cccccc",
                    },
                    "theme/3": {
                        "name": "gonna",
                        "primary_500": "#dddddd",
                        "accent_500": "#eeeeee",
                        "warn_500": "#ffffff",
                    },
                },
            ),
            (
                "meeting.create",
                [
                    {
                        "name": "let you down.",
                        "committee_id": 60,
                        "language": "en",
                        "location": "Never gonna run around and desert you.",
                        "description": "Never gonna make you cry.",
                        "admin_ids": [1],
                    }
                ],
                [{"id": 2}],
                {
                    "meeting/2": {
                        "name": "let you down.",
                        "committee_id": 60,
                        "language": "en",
                        "location": "Never gonna run around and desert you.",
                        "description": "Never gonna make you cry.",
                    },
                    "meeting_user/2": {"user_id": 1, "meeting_id": 2},
                },
            ),  # legacy for now
        ],
        [
            (
                "organization_tag.delete",
                [{"id": id_} for id_ in [1, 2]],
                None,
                {"organization_tag/2": None},
            ),
            (
                "motion.create",
                [
                    {
                        "meeting_id": 1,
                        "title": "Never gonna",
                        "text": "SAYYYYYYY goodbye.",
                    }
                ],
                [{"id": 2, "sequential_number": 2}],
                {
                    "motion/2": {
                        "meeting_id": 1,
                        "title": "Never gonna",
                        "text": "SAYYYYYYY goodbye.",
                    },
                    "list_of_speakers/2": {"content_object_id": "motion/2"},
                },
            ),  # legacy for now
            (
                "motion_workflow.update",
                [{"id": 2, "name": "Never"}],
                [None],
                {"motion_workflow/2": {"name": "Never"}},
            ),
            (
                "topic.create",
                [
                    {"title": "gonna", "meeting_id": 1},
                ],
                [{"id": 1, "sequential_number": 1}],
                {
                    "topic/1": {"title": "gonna", "meeting_id": 1},
                    "agenda_item/1": {"content_object_id": "topic/1", "meeting_id": 1},
                },
            ),  # legacy for now
            (
                "theme.update",
                [
                    {"id": 2, "name": "tell"},
                    {"id": 3, "name": "a"},
                ],
                [None, None],
                {"theme/2": {"name": "tell"}, "theme/3": {"name": "a"}},
            ),
            (
                "user.create",
                [{"username": "lie", "email": "and.hurt@you.de"}],
                [{"id": 2}],
                {"user/2": {"username": "lie", "email": "and.hurt@you.de"}},
            ),  # legacy for now
        ],
        [
            ("motion.delete", [{"id": 2}], None, {"motion/2": None}),  # legacy for now
            (
                "organization.delete_history_information",
                [{"id": 1}],
                None,
                {f"history_position/{id_}": None for id_ in [1, 2, 3, 4, 5]},
            ),
            (
                "meeting.update",
                [{"id": id_, "time_zone": "Europe/Berlin"} for id_ in [1, 2]],
                [None, None],
                {f"meeting/{id_}": {"time_zone": "Europe/Berlin"} for id_ in [1, 2]},
            ),
        ],
    ]

    def setUp(self) -> None:
        super().setUp()
        self.create_meeting()
        self.create_motion(1)

    def test_test_validity(self) -> None:
        count_dda = 0
        count_legacy = 0
        has_mixed_tests = False
        for case_iteration in self.case_actions:
            count_iter_dda = 0
            count_iter_legacy = 0
            action_names = {action_name for action_name, _, _, _ in case_iteration}
            for action_name in action_names:
                if actions_map[action_name].legacy:
                    count_legacy += 1
                    count_iter_legacy += 1
                else:
                    count_dda += 1
                    count_iter_dda += 1
            if count_iter_legacy and count_iter_dda:
                has_mixed_tests = True
        assert (
            has_mixed_tests
        ), "This test order needs to be switched up or this testclass is pointless"
        assert count_legacy > 0, "No legacy actions left."
        assert count_dda > 0, "Where did all the DDActions go?"

    def test_parse_actions_normal(self) -> None:
        for case_iteration in self.case_actions:
            response = self.request_json(
                [
                    {
                        "action": action_name,
                        "data": payloads,
                    }
                    for action_name, payloads, _, _ in case_iteration
                ],
            )
            self.assert_status_code(response, 200)
            all_results: list[ActionResults | None] = []
            for _, _, results, expected in case_iteration:
                all_results.append(results)
                for fqid, expected_data in expected.items():
                    if expected_data:
                        self.assert_model_exists(fqid, expected_data)
                    else:
                        self.assert_model_not_exists(fqid)
            assert response.json["results"] == all_results

    def test_parse_actions_non_atomic(self) -> None:
        for i, case_iteration in enumerate(self.case_actions):
            response = self.request_json(
                [
                    {
                        "action": action_name,
                        "data": payloads,
                    }
                    for action_name, payloads, _, _ in case_iteration
                ],
                atomic=False,
            )
            try:
                self.assert_status_code(response, 200)
                all_results: list[ActionResults | None] = []
                for _, _, results, expected in case_iteration:
                    all_results.append(results)
                    for fqid, expected_data in expected.items():
                        if expected_data:
                            self.assert_model_exists(fqid, expected_data)
                        else:
                            self.assert_model_not_exists(fqid)
                assert response.json["results"] == all_results
            except Exception as e:
                raise e

    def test_parse_actions_internal(self) -> None:
        for case_iteration in self.case_actions:
            response = self.request_json(
                [
                    {
                        "action": action_name,
                        "data": payloads,
                    }
                    for action_name, payloads, _, _ in case_iteration
                ],
                internal=True,
            )
            self.assert_status_code(response, 200)
            all_results: list[ActionResults | None] = []
            for _, _, results, expected in case_iteration:
                all_results.append(results)
                for fqid, expected_data in expected.items():
                    if expected_data:
                        self.assert_model_exists(fqid, expected_data)
                    else:
                        self.assert_model_not_exists(fqid)
            assert response.json["results"] == all_results
