from openslides_backend.action.generics.create import CreateAction
from openslides_backend.action.util.register import register_action
from openslides_backend.models import fields
from openslides_backend.models.base import model_registry
from openslides_backend.permissions.management_levels import OrganizationManagementLevel
from openslides_backend.permissions.permissions import Permissions
from openslides_backend.services.postgresql.db_connection_handling import (
    get_new_os_conn,
)
from tests.patch_model_registry_helper import (
    FakeModel,
    PatchModelRegistryMixin,
    fake_registry,
)

from .base import BaseActionTestCase

collection_p = "fake_model_p"


def create_table_view() -> None:
    sql = f"""
    CREATE TABLE IF NOT EXISTS {collection_p}_t (
        id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        meeting_id integer
    );

    DROP VIEW IF EXISTS "{collection_p}";
    CREATE VIEW "{collection_p}" AS SELECT * FROM {collection_p}_t;
    """
    with get_new_os_conn() as conn:
        with conn.cursor() as curs:
            curs.execute(sql)


class FakeModelP(FakeModel):
    collection = "fake_model_p"
    verbose_name = "fake model for permissions"
    id = fields.IntegerField()
    meeting_id = fields.IntegerField()


@register_action("fake_model_p.create")
class FakeModelPCreate(CreateAction):
    model = FakeModelP()
    schema = {}  # type: ignore
    permission = Permissions.Motion.CAN_CREATE


class TestPermissions(PatchModelRegistryMixin, BaseActionTestCase):
    fake_model_registry = model_registry | fake_registry
    init_with_login = True

    @classmethod
    def setUpClass(cls) -> None:
        super().setUpClass()
        create_table_view()

    @classmethod
    def tearDownClass(cls) -> None:
        super().tearDownClass()
        with get_new_os_conn() as conn:
            with conn.cursor() as curs:
                curs.execute(f"DROP TABLE {collection_p}_t CASCADE;")

    def setUp(self) -> None:
        super().setUp()
        self.create_meeting()
        self.set_organization_management_level(None)

    def tearDown(self) -> None:
        super().tearDown()
        with self.connection.cursor() as curs:
            curs.execute(
                f"""
                TRUNCATE TABLE {collection_p}_t RESTART IDENTITY;
                """
            )

    def test_anonymous_disabled(self) -> None:
        self.set_anonymous(False)
        response = self.request(
            "fake_model_p.create", {"meeting_id": 1}, anonymous=True
        )
        self.assert_status_code(response, 403)
        assert response.json["message"] == "Anonymous is not enabled for meeting 1"

    def test_anonymous_no_permission(self) -> None:
        self.set_anonymous(True)
        # 1 is default group
        self.set_group_permissions(1, [])
        response = self.request(
            "fake_model_p.create", {"meeting_id": 1}, anonymous=True
        )
        self.assert_status_code(response, 403)
        assert (
            response.json["message"]
            == "You are not allowed to perform action fake_model_p.create. Missing Permission: motion.can_create"
        )

    def test_anonymous_valid(self) -> None:
        self.set_anonymous(True, permissions=[Permissions.Motion.CAN_CREATE])
        response = self.request(
            "fake_model_p.create", {"meeting_id": 1}, anonymous=True
        )
        self.assert_status_code(response, 200)
        self.assert_model_exists("fake_model_p/1")

    def test_not_related_user(self) -> None:
        response = self.request("fake_model_p.create", {"meeting_id": 1})
        self.assert_status_code(response, 403)
        assert (
            response.json["message"]
            == "You are not allowed to perform action fake_model_p.create. Missing Permission: motion.can_create"
        )

    def test_superadmin(self) -> None:
        self.set_organization_management_level(OrganizationManagementLevel.SUPERADMIN)
        response = self.request("fake_model_p.create", {"meeting_id": 1})
        self.assert_status_code(response, 200)
        self.assert_model_exists("fake_model_p/1")

    def test_orgaadmin(self) -> None:
        self.set_organization_management_level(
            OrganizationManagementLevel.CAN_MANAGE_ORGANIZATION
        )
        response = self.request("fake_model_p.create", {"meeting_id": 1})
        self.assert_status_code(response, 200)
        self.assert_model_exists("fake_model_p/1")

    def test_user_in_admin_group(self) -> None:
        # 2 is admin group
        self.set_user_groups(1, [2])
        response = self.request("fake_model_p.create", {"meeting_id": 1})
        self.assert_status_code(response, 200)
        self.assert_model_exists("fake_model_p/1")

    def test_user_in_some_group(self) -> None:
        self.set_user_groups(1, [3])
        self.set_group_permissions(3, [Permissions.Motion.CAN_CREATE])
        response = self.request("fake_model_p.create", {"meeting_id": 1})
        self.assert_status_code(response, 200)
        self.assert_model_exists("fake_model_p/1")

    def test_user_has_parent_perm(self) -> None:
        self.set_user_groups(1, [3])
        self.set_group_permissions(3, [Permissions.Motion.CAN_MANAGE])
        response = self.request("fake_model_p.create", {"meeting_id": 1})
        self.assert_status_code(response, 200)
        self.assert_model_exists("fake_model_p/1")

    def test_user_has_child_perm(self) -> None:
        self.set_user_groups(1, [3])
        self.set_group_permissions(3, [Permissions.Motion.CAN_SEE])
        response = self.request("fake_model_p.create", {"meeting_id": 1})
        self.assert_status_code(response, 403)
        assert (
            response.json["message"]
            == "You are not allowed to perform action fake_model_p.create. Missing Permission: motion.can_create"
        )
