FROM python:3.10.3-slim-buster

RUN apt-get -y update && apt-get install --no-install-recommends -y \
    postgresql-client libpq-dev gcc libc-dev

WORKDIR /app

COPY requirements_production.txt .
COPY requirements_development.txt .
RUN pip install -r requirements_development.txt

COPY scripts/entrypoint.sh .
COPY scripts/execute-cleanup.sh .
COPY setup.cfg .
COPY scripts/service_env.sh scripts/

EXPOSE 9006

ENV FLASK_APP ./src/mediaserver.py
ENV FLASK_ENV development

ENTRYPOINT ["./entrypoint.sh"]
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "9006"]
