FROM python:3.10.3-slim-buster

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it \
    postgresql-client libpq-dev gcc libc-dev git

WORKDIR /app

COPY requirements*.txt ./
RUN pip install -r requirements_tests.txt

COPY setup.cfg .
COPY src/* src/
COPY scripts/entrypoint.sh .
COPY scripts/service_env.sh scripts/

RUN chmod 777 -R .

STOPSIGNAL SIGKILL
ENTRYPOINT ["./entrypoint.sh"]
CMD ["sleep", "inf"]
