FROM python:3.8.1

RUN apt-get -y update && apt-get install --no-install-recommends -y \
    postgresql-client

WORKDIR /app

COPY requirements_production.txt .
COPY requirements_development.txt .
RUN pip install -r requirements_development.txt

COPY entrypoint.sh .
COPY execute-cleanup.sh .
COPY setup.cfg .

EXPOSE 9006

ENV FLASK_APP ./src/mediaserver.py
ENV FLASK_ENV development

ENTRYPOINT ["./entrypoint.sh"]
CMD ["flask", "run", "--host", "0.0.0.0", "--port", "9006"]
