FROM python:3.8-alpine

RUN apk add build-base

WORKDIR /srv/code

EXPOSE 8000

COPY requirements.txt .
COPY requirements_production.txt .
RUN pip install -U -r requirements.txt

COPY gunicorn_conf.py .
COPY openslides_backend/ ./openslides_backend/

CMD [ "gunicorn", "--config=python:gunicorn_conf", "--reload", "openslides_backend.wsgi:application" ]
