FROM python:3.8.1

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it

WORKDIR /app

COPY requirements_tests.txt requirements_tests.txt
RUN pip install -r requirements_tests.txt
COPY requirements_development.txt requirements_development.txt
RUN pip install -r requirements_development.txt

COPY entrypoint-tests.sh .
COPY setup.cfg .

ENTRYPOINT ["./entrypoint-tests.sh"]
