FROM python:3.8.1

RUN apt-get -y update && apt-get -y upgrade && \
    apt-get install --no-install-recommends -y wait-for-it

WORKDIR /app

COPY requirements_tests.txt requirements_tests.txt
RUN pip install -r requirements_tests.txt

CMD ["bash", "-c", "sleep infinity"]
