FROM python:3.8.1-alpine3.11

ARG OPENSLIDES_BACKEND_ACTIONS_PORT=9002
ARG OPENSLIDES_BACKEND_PRESENTER_PORT=9003

ENV OPENSLIDES_BACKEND_COMPONENT=all
ENV OPENSLIDES_BACKEND_DEBUG 1

WORKDIR /srv/code

RUN apk add --no-cache gcc musl-dev linux-headers git

COPY requirements.txt .
COPY requirements_production.txt .

RUN pip install --no-cache-dir --requirement requirements.txt

COPY openslides_backend/ ./openslides_backend/
COPY setup.cfg .

EXPOSE ${OPENSLIDES_BACKEND_ACTIONS_PORT}
EXPOSE ${OPENSLIDES_BACKEND_PRESENTER_PORT}

CMD [ "python", "-m", "openslides_backend" ]
