from psycopg import Cursor
from psycopg.rows import DictRow

from openslides_backend.migrations.migrations.base import BaseMigration


class Migration(BaseMigration):
    ORIGIN_COLLECTIONS = [
        "meeting",
        "assignment",
        "meeting_user",
        "assignment_candidate",
    ]

    # @staticmethod
    #     def data_definition(curs: Cursor[DictRow]) -> None:
    #         MigrationHelper.delete_collection(curs, "assignment_candidate")
    #         MigrationHelper.create_collection(
    #             curs,
    #             "assignment_category",
    #             AssignmentCategory,
    #             """CREATE TABLE assignment_category_t (
    #     id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    #     name varchar(256)
    #         CONSTRAINT required_assignment_category_name NOT NULL,
    #     prefix varchar(256),
    #     weight integer
    #         CONSTRAINT default_assignment_category_weight DEFAULT 10000,
    #     level integer,
    #     sequential_number integer
    #         CONSTRAINT required_assignment_category_sequential_number NOT NULL,
    #     CONSTRAINT unique_assignment_category_sequential_number_meeting_id UNIQUE (sequential_number, meeting_id),
    #     parent_id integer,
    #     meeting_id integer
    #         CONSTRAINT required_assignment_category_meeting_id NOT NULL
    # );""",
    #         )
    #         MigrationHelper.create_field(
    #             curs, "integer", "assignment", "category_id", "assignment_category"
    #         )
    #         MigrationHelper.rename_field(
    #             curs, "meeting", "motions_number_type", "motions_assignments_number_type"
    #         )
    #         # relations to deleted models
    #         # MigrationHelper.delete_field(curs, "meeting", "assignment_candidate_ids")
    #         # MigrationHelper.delete_field(curs, "assignment", "candidate_ids")
    #         # MigrationHelper.delete_field(curs, "meeting_user", "assignment_candidate_ids")

    @staticmethod
    def data_manipulation(curs: Cursor[DictRow]) -> None:
        pass

    @staticmethod
    def cleanup(curs: Cursor[DictRow]) -> None:
        pass
