# Use local datastore instead of pip package
version: "3"
services:
    backend:
        build:
            args:
                - REQUIREMENTS_FILE=requirements_development_local.txt
        volumes:
            - ../../openslides-datastore-service/:/datastore-service
            - ../../openslides-auth-service/auth/libraries/pip-auth/:/authlib
        environment:
            - PYTHONPATH=/app:/datastore-service:/authlib
            - MYPYPATH=/app:/datastore-service:/authlib
    vote:
        build:
            context: ../../openslides-vote-service
    auth:
        build:
            context: ../../openslides-auth-service
