# Use local auth and vote service
version: "3"
services:
    backend:
        build:
            context: ..
            args:
                REQUIREMENTS_FILE_OVERWRITE: "requirements_development_local.txt"
                CONTEXT: "dev"
        volumes:
            - ../../openslides-auth-service/auth/libraries/pip-auth/:/osauthlib
        environment:
            - PYTHONPATH=/app:/osauthlib
            - MYPYPATH=/app:/osauthlib
    vote:
        build:
            context: ../../openslides-vote-service
            args:
                CONTEXT: "prod"
    auth:
        build:
            context: ../../openslides-auth-service
            args:
                CONTEXT: "prod"
