# Use local datastore instead of pip package
version: "3"
services:
    backend:
        build:
            args:
                - REQUIREMENTS_FILE=requirements_development_local.txt
        volumes:
            - ../../openslides-datastore-service/:/datastore-service
            - ../../openslides-auth-service/auth/libraries/pip-auth/:/authlib
        environment:
            - PYTHONPATH=/app:/datastore-service:/authlib
            - MYPYPATH=/app:/datastore-service:/authlib
    datastore-writer:
        build:
            context: ../../openslides-datastore-service/
            dockerfile: Dockerfile.dev
            args:
                MODULE: "writer"
                PORT: "9011"
        image: openslides-datastore-writer-dev
        ports:
            - "9011:9011"
            - "5679:5678"
        environment:
            - OPENSLIDES_DEVELOPMENT=1
            - DATABASE_NAME=openslides
            - DATABASE_USER=openslides
            - DATABASE_HOST=postgres
            - MESSAGE_BUS_HOST=redis
        volumes:
            - ../../openslides-datastore-service/datastore:/app/datastore
            - ../../openslides-datastore-service/cli:/app/cli
    vote:
        build:
            context: ../../openslides-vote-service
    auth:
        build:
            context: ../../openslides-auth-service
