# Use local datastore instead of pip package
version: "3"
services:
    backend:
        build:
            args:
                - REQUIREMENTS_FILE=requirements_development_local_ds.txt
        volumes:
            - ../../openslides-datastore-service/:/datastore-service
        environment:
            - PYTHONPATH=/app:/datastore-service
            - MYPYPATH=/app:/datastore-service
    datastore-writer:
        build:
            context: ../../openslides-datastore-service/
            dockerfile: Dockerfile.dev
            args:
                MODULE: "writer"
                PORT: "9011"
        image: openslides-datastore-writer-dev
        ports:
            - "9011:9011"
            - "5679:5678"
        environment:
            - OPENSLIDES_DEVELOPMENT=1
            - DATASTORE_ENABLE_DEV_ENVIRONMENT=1
            - DATASTORE_DATABASE_NAME=openslides
            - DATASTORE_DATABASE_USER=openslides
            - DATASTORE_DATABASE_HOST=postgres
            - MESSAGE_BUS_HOST=redis
        volumes:
            - ../../openslides-datastore-service/datastore:/app/datastore
            - ../../openslides-datastore-service/cli:/app/cli
    vote:
        build:
            context: ../../openslides-vote-service
    auth:
        build:
            context: ../../openslides-auth-service
