# Use local auth and vote service
version: "3"
services:
    backend:
        build:
            context: ..
            args:
                REQUIREMENTS_FILE_OVERWRITE: "requirements_development_local.txt"
                CONTEXT: "dev"
        volumes:
            - ../../openslides-auth-service/auth/libraries/pip-auth/:/authlib
        environment:
            - PYTHONPATH=/app:/authlib
            - MYPYPATH=/app:/authlib
    vote:
        build:
            context: ../../openslides-vote-service
    auth:
        build:
            context: ../../openslides-auth-service
