# Use local auth and vote service
version: "3"
services:
    backend:
        build:
            context: ..
            args:
                REQUIREMENTS_FILE_OVERWRITE: "requirements_development_local.txt"
                CONTEXT: "dev"
    vote:
        build:
            context: ../../openslides-vote-service
            args:
                CONTEXT: "prod"
    auth:
        build:
            context: ../../openslides-auth-service
            args:
                CONTEXT: "prod"
