version: "3"
services:
  backend:
    environment:
      - OPENTELEMETRY_ENABLED=1
  reader:
    environment:
      - OPENTELEMETRY_ENABLED=1
  writer:
    environment:
      - OPENTELEMETRY_ENABLED=1
  auth:
    environment:
      - OPENTELEMETRY_ENABLED=1
  vote:
    environment:
      - OPENTELEMETRY_ENABLED=1

  collector:
    image: otel/opentelemetry-collector:0.41.0
    command: ["--config=/etc/otel-collector-config.yml"]
    volumes:
      - ./otel-collector-config.yml:/etc/otel-collector-config.yml
    networks:
      - datastore
      - auth
      - otel

  jaeger:
    image: jaegertracing/all-in-one
    ports:
      - "16686:16686"
    networks:
      - otel

networks:
  otel:
