FROM python:3.8.5-slim-buster

RUN apt-get update && apt-get install --yes make git curl ncat vim bash-completion mime-support gcc libpq-dev

WORKDIR /app
RUN mkdir migrations

COPY requirements/ requirements/
ARG REQUIREMENTS_FILE=requirements_development.txt
RUN . requirements/export_datastore_commit.sh && pip install --no-cache-dir --requirement requirements/$REQUIREMENTS_FILE

COPY dev/.bashrc .
COPY dev/cleanup.sh .

# Copy files which are mounted to make the full stack work
COPY scripts scripts
COPY global global
COPY cli cli

COPY Makefile .
COPY setup.cfg .
COPY dev/entrypoint.sh ./

RUN chmod 777 -R .
RUN chmod 777 /root
RUN chmod 777 -R /usr/local/lib/

EXPOSE 9002
EXPOSE 9003
EXPOSE 5678

ENV OPENSLIDES_DEVELOPMENT 1
ENV PYTHONPATH /app

ENV EMAIL_HOST postfix
ENV EMAIL_PORT 25
# ENV EMAIL_HOST_USER username
# ENV EMAIL_HOST_PASSWORD secret
# EMAIL_CONNECTION_SECURITY use NONE, STARTTLS or SSL/TLS
ENV EMAIL_CONNECTION_SECURITY NONE
ENV EMAIL_TIMEOUT 5
ENV EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE false
ENV DEFAULT_FROM_EMAIL noreply@example.com

ENTRYPOINT ["./entrypoint.sh"]
CMD ["python", "-m", "debugpy", "--listen", "0.0.0.0:5678", "openslides_backend"]
