FROM python:3.8.5-slim-buster

RUN apt-get update && apt-get install --yes make git curl ncat

WORKDIR /srv/code
COPY requirements.txt .
COPY setup.cfg .
COPY Makefile Makefile
COPY dev dev

RUN pip install --no-cache-dir --requirement dev/requirements_development.txt

EXPOSE 9002
EXPOSE 9003

ENV OPENSLIDES_BACKEND_DEBUG 1

CMD [ "python", "-m", "openslides_backend" ]
