FROM python:3.8.5-slim-buster

RUN apt-get update && apt-get install --yes make git curl ncat vim bash-completion

WORKDIR /app
RUN mkdir dev

COPY requirements.txt .
COPY dev/requirements_development.txt dev/.

RUN pip install --no-cache-dir --requirement dev/requirements_development.txt

COPY dev/wait.sh dev/.
COPY dev/run-tests.sh dev/.
COPY dev/bashrc dev/.
COPY dev/cleanup.sh .

COPY Makefile Makefile
COPY setup.cfg .

RUN chmod 777 -R .
RUN chmod 777 /root

EXPOSE 9002
EXPOSE 9003
EXPOSE 5678

ENV OPENSLIDES_DEVELOPMENT 1

CMD python -m debugpy --listen 0.0.0.0:5678 openslides_backend
