FROM python:3.12.9-slim-bookworm

RUN apt-get update && apt-get install --yes \
    make git curl ncat vim bash-completion mime-support gcc libpq-dev libmagic1 postgresql-client

WORKDIR /app

COPY requirements/ requirements/
ARG REQUIREMENTS_FILE=requirements_development.txt
RUN . requirements/export_service_commits.sh && pip install --no-cache-dir --requirement requirements/$REQUIREMENTS_FILE

COPY dev/.bashrc .
COPY dev/cleanup.sh .

# Copy files which are mounted to make the full stack work
COPY scripts scripts
COPY cli cli
COPY data data
COPY meta meta

COPY Makefile .
COPY setup.cfg .
COPY dev/entrypoint.sh ./

RUN chmod 777 -R .

EXPOSE 9002
EXPOSE 9003
EXPOSE 5678

ENV OPENSLIDES_DEVELOPMENT 1
ENV PYTHONPATH /app

ENV EMAIL_HOST postfix
ENV EMAIL_PORT 25
# ENV EMAIL_HOST_USER username
# ENV EMAIL_HOST_PASSWORD secret
# EMAIL_CONNECTION_SECURITY use NONE, STARTTLS or SSL/TLS
ENV EMAIL_CONNECTION_SECURITY NONE
ENV EMAIL_TIMEOUT 5
ENV EMAIL_ACCEPT_SELF_SIGNED_CERTIFICATE false
ENV DEFAULT_FROM_EMAIL noreply@example.com

STOPSIGNAL SIGKILL
ENTRYPOINT ["./entrypoint.sh"]
CMD exec python -m debugpy --listen 0.0.0.0:5678 openslides_backend
