FROM python:3.8.5-slim-buster

RUN apt-get update && apt-get install --yes make git curl ncat vim

WORKDIR /app
RUN mkdir dev

COPY requirements.txt .
COPY dev/requirements_development.txt dev/.

RUN pip install --no-cache-dir --requirement dev/requirements_development.txt

COPY dev/wait.sh dev/.
COPY dev/run-tests.sh dev/.
COPY dev/cleanup.sh .

COPY Makefile Makefile
COPY setup.cfg .

RUN chmod 777 -R .
RUN chmod 777 /root

EXPOSE 9002
EXPOSE 9003

ENV OS4_DEVELOPMENT 1

CMD [ "python", "-m", "openslides_backend" ]
