from . import (  # noqa
    archive,
    clone,
    create,
    delete,
    delete_all_speakers_of_all_lists,
    import_,
    replace_projector_id,
    set_font,
    set_logo,
    unarchive,
    unset_font,
    unset_logo,
    update,
)
