CREATE TABLE assignment_category_t (
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name varchar(256)
        CONSTRAINT required_assignment_category_name NOT NULL,
    prefix varchar(256),
    weight integer
        CONSTRAINT default_assignment_category_weight DEFAULT 10000,
    level integer,
    sequential_number integer
        CONSTRAINT required_assignment_category_sequential_number NOT NULL,
    CONSTRAINT unique_assignment_category_sequential_number_meeting_id UNIQUE (sequential_number, meeting_id),
    parent_id integer,
    meeting_id integer
        CONSTRAINT required_assignment_category_meeting_id NOT NULL
);
ALTER TABLE assignment_t ADD COLUMN category_id integer;

CREATE VIEW "assignment_category" AS SELECT *,
(select array_agg(ac.id ORDER BY ac.id) from assignment_category_t ac where ac.parent_id = a.id) as child_ids,
(select array_agg(ast.id ORDER BY ast.id) from assignment_t ast where ast.category_id = a.id) as assignment_ids
FROM assignment_category_t a;

ALTER TYPE enum_meeting_motions_number_type RENAME TO enum_meeting_motions_assignments_number_type;
ALTER TABLE meeting_t ADD COLUMN assignment_category_ids integer[];
ALTER TABLE meeting_t ADD COLUMN motions_assignments_number_type enum_meeting_motions_assignments_number_type
        CONSTRAINT default_meeting_motions_assignments_number_type DEFAULT 'per_category';
ALTER TABLE agenda_item_t ALTER COLUMN type DROP DEFAULT;
ALTER TABLE agenda_item_t ALTER COLUMN type SET DEFAULT 'hidden';

ALTER TABLE assignment_t ADD CONSTRAINT fk_assignment_t_category_id_assignment_category_t_id FOREIGN KEY(category_id) REFERENCES assignment_category_t(id) INITIALLY DEFERRED;
CREATE INDEX idx_assignment_t_category_id ON assignment_t (category_id);
ALTER TABLE assignment_category_t ADD CONSTRAINT fk_assignment_category_t_parent_id_assignment_category_t_id FOREIGN KEY(parent_id) REFERENCES assignment_category_t(id) INITIALLY DEFERRED;
CREATE INDEX idx_assignment_category_t_parent_id ON assignment_category_t (parent_id);
ALTER TABLE assignment_category_t ADD CONSTRAINT fk_assignment_category_t_meeting_id_meeting_t_id FOREIGN KEY(meeting_id) REFERENCES meeting_t(id) INITIALLY DEFERRED;
CREATE INDEX idx_assignment_category_t_meeting_id ON assignment_category_t (meeting_id);