def test_migration(write, finalize, assert_model):
    write(
        {
            "type": "create",
            "fqid": "motion_state/11",
            "fields": {
                "id": 11,
                "name": "received",
                "recommendation_label": "receival",
                "css_class": "lightblue",
                "restrictions": [],
                "allow_support": False,
                "allow_create_poll": False,
                "allow_submitter_edit": False,
                "set_number": True,
                "show_state_extension_field": False,
                "merge_amendment_into_final": "do_not_merge",
                "show_recommendation_extension_field": False,
                "weight": 1,
            },
        },
        {
            "type": "create",
            "fqid": "motion_state/12",
            "fields": {
                "id": 12,
                "name": "failed",
                "recommendation_label": "failure",
                "css_class": "red",
                "restrictions": [],
                "allow_support": False,
                "allow_create_poll": False,
                "allow_submitter_edit": False,
                "set_workflow_timestamp": True,
                "set_number": True,
                "show_state_extension_field": False,
                "merge_amendment_into_final": "do_not_merge",
                "show_recommendation_extension_field": False,
                "weight": 2,
            },
        },
        {
            "type": "create",
            "fqid": "motion_state/13",
            "fields": {
                "id": 13,
                "name": "successful",
                "recommendation_label": "success",
                "css_class": "green",
                "restrictions": [],
                "allow_support": False,
                "allow_create_poll": False,
                "allow_submitter_edit": False,
                "allow_motion_forwarding": False,
                "set_number": True,
                "show_state_extension_field": False,
                "merge_amendment_into_final": "do_not_merge",
                "show_recommendation_extension_field": False,
                "weight": 3,
            },
        },
        {
            "type": "create",
            "fqid": "motion_state/14",
            "fields": {
                "id": 14,
                "name": "illegal",
                "recommendation_label": "illegalize",
                "css_class": "lightblue",
                "restrictions": [],
                "allow_support": False,
                "allow_create_poll": False,
                "allow_submitter_edit": False,
                "allow_motion_forwarding": False,
                "set_workflow_timestamp": True,
                "set_number": True,
                "show_state_extension_field": False,
                "merge_amendment_into_final": "do_not_merge",
                "show_recommendation_extension_field": False,
                "weight": 4,
            },
        },
    )

    finalize("0047_add_workflow_state_boolean_defaults")

    assert_model(
        "motion_state/11",
        {
            "id": 11,
            "name": "received",
            "recommendation_label": "receival",
            "css_class": "lightblue",
            "restrictions": [],
            "allow_support": False,
            "allow_create_poll": False,
            "allow_submitter_edit": False,
            "set_number": True,
            "show_state_extension_field": False,
            "merge_amendment_into_final": "do_not_merge",
            "show_recommendation_extension_field": False,
            "weight": 1,
            "allow_motion_forwarding": False,
            "set_workflow_timestamp": False,
        },
    )
    assert_model(
        "motion_state/12",
        {
            "id": 12,
            "name": "failed",
            "recommendation_label": "failure",
            "css_class": "red",
            "restrictions": [],
            "allow_support": False,
            "allow_create_poll": False,
            "allow_submitter_edit": False,
            "set_number": True,
            "show_state_extension_field": False,
            "merge_amendment_into_final": "do_not_merge",
            "show_recommendation_extension_field": False,
            "weight": 2,
            "allow_motion_forwarding": False,
            "set_workflow_timestamp": True,
        },
    )
    assert_model(
        "motion_state/13",
        {
            "id": 13,
            "name": "successful",
            "recommendation_label": "success",
            "css_class": "green",
            "restrictions": [],
            "allow_support": False,
            "allow_create_poll": False,
            "allow_submitter_edit": False,
            "set_number": True,
            "show_state_extension_field": False,
            "merge_amendment_into_final": "do_not_merge",
            "show_recommendation_extension_field": False,
            "weight": 3,
            "allow_motion_forwarding": False,
            "set_workflow_timestamp": False,
        },
    )
    assert_model(
        "motion_state/14",
        {
            "id": 14,
            "name": "illegal",
            "recommendation_label": "illegalize",
            "css_class": "lightblue",
            "restrictions": [],
            "allow_support": False,
            "allow_create_poll": False,
            "allow_submitter_edit": False,
            "set_number": True,
            "show_state_extension_field": False,
            "merge_amendment_into_final": "do_not_merge",
            "show_recommendation_extension_field": False,
            "weight": 4,
            "allow_motion_forwarding": False,
            "set_workflow_timestamp": True,
        },
    )
