#!/bin/bash
set -e

export MEDIA_DATABASE_HOST="${MEDIA_DATABASE_HOST:-db}"
export MEDIA_DATABASE_PORT="${MEDIA_DATABASE_PORT:-5432}"
export MEDIA_DATABASE_NAME="${MEDIA_DATABASE_NAME:-mediafiledata}"
if [ -n "$MEDIA_DATABASE_USER_FILE" ];
then
	MEDIA_DATABASE_USER=$(cat $MEDIA_DATABASE_USER_FILE)
fi;
if [ -n "$MEDIA_DATABASE_PASSWORD_FILE" ];
then
	MEDIA_DATABASE_PASSWORD=$(cat $MEDIA_DATABASE_PASSWORD_FILE)
fi;
export MEDIA_DATABASE_USER="${MEDIA_DATABASE_USER:-openslides}"
export MEDIA_DATABASE_PASSWORD="${MEDIA_DATABASE_PASSWORD:-openslides}"
