# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: restricter.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='restricter.proto',
  package='restricter',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10restricter.proto\x12\nrestricter\"-\n\x0fRestrictRequest\x12\x0c\n\x04user\x18\x01 \x01(\x03\x12\x0c\n\x04keys\x18\x02 \x03(\t\"i\n\nRestricted\x12.\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32 .restricter.Restricted.DataEntry\x1a+\n\tDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\'\n\nIDsRequest\x12\x0c\n\x04user\x18\x01 \x01(\x03\x12\x0b\n\x03key\x18\x02 \x01(\t\"\x12\n\x03IDs\x12\x0b\n\x03ids\x18\x01 \x03(\x03\x32\x7f\n\x08Restrict\x12\x41\n\x08restrict\x12\x1b.restricter.RestrictRequest\x1a\x16.restricter.Restricted\"\x00\x12\x30\n\x03ids\x12\x16.restricter.IDsRequest\x1a\x0f.restricter.IDs\"\x00\x62\x06proto3')
)




_RESTRICTREQUEST = _descriptor.Descriptor(
  name='RestrictRequest',
  full_name='restricter.RestrictRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='restricter.RestrictRequest.user', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keys', full_name='restricter.RestrictRequest.keys', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=77,
)


_RESTRICTED_DATAENTRY = _descriptor.Descriptor(
  name='DataEntry',
  full_name='restricter.Restricted.DataEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='restricter.Restricted.DataEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='restricter.Restricted.DataEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=_b('8\001'),
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=141,
  serialized_end=184,
)

_RESTRICTED = _descriptor.Descriptor(
  name='Restricted',
  full_name='restricter.Restricted',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='restricter.Restricted.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_RESTRICTED_DATAENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=79,
  serialized_end=184,
)


_IDSREQUEST = _descriptor.Descriptor(
  name='IDsRequest',
  full_name='restricter.IDsRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='restricter.IDsRequest.user', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key', full_name='restricter.IDsRequest.key', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=225,
)


_IDS = _descriptor.Descriptor(
  name='IDs',
  full_name='restricter.IDs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ids', full_name='restricter.IDs.ids', index=0,
      number=1, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=227,
  serialized_end=245,
)

_RESTRICTED_DATAENTRY.containing_type = _RESTRICTED
_RESTRICTED.fields_by_name['data'].message_type = _RESTRICTED_DATAENTRY
DESCRIPTOR.message_types_by_name['RestrictRequest'] = _RESTRICTREQUEST
DESCRIPTOR.message_types_by_name['Restricted'] = _RESTRICTED
DESCRIPTOR.message_types_by_name['IDsRequest'] = _IDSREQUEST
DESCRIPTOR.message_types_by_name['IDs'] = _IDS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RestrictRequest = _reflection.GeneratedProtocolMessageType('RestrictRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESTRICTREQUEST,
  '__module__' : 'restricter_pb2'
  # @@protoc_insertion_point(class_scope:restricter.RestrictRequest)
  })
_sym_db.RegisterMessage(RestrictRequest)

Restricted = _reflection.GeneratedProtocolMessageType('Restricted', (_message.Message,), {

  'DataEntry' : _reflection.GeneratedProtocolMessageType('DataEntry', (_message.Message,), {
    'DESCRIPTOR' : _RESTRICTED_DATAENTRY,
    '__module__' : 'restricter_pb2'
    # @@protoc_insertion_point(class_scope:restricter.Restricted.DataEntry)
    })
  ,
  'DESCRIPTOR' : _RESTRICTED,
  '__module__' : 'restricter_pb2'
  # @@protoc_insertion_point(class_scope:restricter.Restricted)
  })
_sym_db.RegisterMessage(Restricted)
_sym_db.RegisterMessage(Restricted.DataEntry)

IDsRequest = _reflection.GeneratedProtocolMessageType('IDsRequest', (_message.Message,), {
  'DESCRIPTOR' : _IDSREQUEST,
  '__module__' : 'restricter_pb2'
  # @@protoc_insertion_point(class_scope:restricter.IDsRequest)
  })
_sym_db.RegisterMessage(IDsRequest)

IDs = _reflection.GeneratedProtocolMessageType('IDs', (_message.Message,), {
  'DESCRIPTOR' : _IDS,
  '__module__' : 'restricter_pb2'
  # @@protoc_insertion_point(class_scope:restricter.IDs)
  })
_sym_db.RegisterMessage(IDs)


_RESTRICTED_DATAENTRY._options = None

_RESTRICT = _descriptor.ServiceDescriptor(
  name='Restrict',
  full_name='restricter.Restrict',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=247,
  serialized_end=374,
  methods=[
  _descriptor.MethodDescriptor(
    name='restrict',
    full_name='restricter.Restrict.restrict',
    index=0,
    containing_service=None,
    input_type=_RESTRICTREQUEST,
    output_type=_RESTRICTED,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ids',
    full_name='restricter.Restrict.ids',
    index=1,
    containing_service=None,
    input_type=_IDSREQUEST,
    output_type=_IDS,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RESTRICT)

DESCRIPTOR.services_by_name['Restrict'] = _RESTRICT

# @@protoc_insertion_point(module_scope)
