// Code generated by protoc-gen-go. DO NOT EDIT.
// source: restricter.proto

package restricter

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type RestrictRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Keys                 []string `protobuf:"bytes,2,rep,name=keys,proto3" json:"keys,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RestrictRequest) Reset()         { *m = RestrictRequest{} }
func (m *RestrictRequest) String() string { return proto.CompactTextString(m) }
func (*RestrictRequest) ProtoMessage()    {}
func (*RestrictRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d2ebd3ec91d9e1b, []int{0}
}

func (m *RestrictRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RestrictRequest.Unmarshal(m, b)
}
func (m *RestrictRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RestrictRequest.Marshal(b, m, deterministic)
}
func (m *RestrictRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RestrictRequest.Merge(m, src)
}
func (m *RestrictRequest) XXX_Size() int {
	return xxx_messageInfo_RestrictRequest.Size(m)
}
func (m *RestrictRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RestrictRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RestrictRequest proto.InternalMessageInfo

func (m *RestrictRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *RestrictRequest) GetKeys() []string {
	if m != nil {
		return m.Keys
	}
	return nil
}

type Restricted struct {
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Restricted) Reset()         { *m = Restricted{} }
func (m *Restricted) String() string { return proto.CompactTextString(m) }
func (*Restricted) ProtoMessage()    {}
func (*Restricted) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d2ebd3ec91d9e1b, []int{1}
}

func (m *Restricted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Restricted.Unmarshal(m, b)
}
func (m *Restricted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Restricted.Marshal(b, m, deterministic)
}
func (m *Restricted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Restricted.Merge(m, src)
}
func (m *Restricted) XXX_Size() int {
	return xxx_messageInfo_Restricted.Size(m)
}
func (m *Restricted) XXX_DiscardUnknown() {
	xxx_messageInfo_Restricted.DiscardUnknown(m)
}

var xxx_messageInfo_Restricted proto.InternalMessageInfo

func (m *Restricted) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type IDsRequest struct {
	User                 int64    `protobuf:"varint,1,opt,name=user,proto3" json:"user,omitempty"`
	Key                  string   `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDsRequest) Reset()         { *m = IDsRequest{} }
func (m *IDsRequest) String() string { return proto.CompactTextString(m) }
func (*IDsRequest) ProtoMessage()    {}
func (*IDsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d2ebd3ec91d9e1b, []int{2}
}

func (m *IDsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDsRequest.Unmarshal(m, b)
}
func (m *IDsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDsRequest.Marshal(b, m, deterministic)
}
func (m *IDsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDsRequest.Merge(m, src)
}
func (m *IDsRequest) XXX_Size() int {
	return xxx_messageInfo_IDsRequest.Size(m)
}
func (m *IDsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_IDsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_IDsRequest proto.InternalMessageInfo

func (m *IDsRequest) GetUser() int64 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *IDsRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type IDs struct {
	Ids                  []int64  `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *IDs) Reset()         { *m = IDs{} }
func (m *IDs) String() string { return proto.CompactTextString(m) }
func (*IDs) ProtoMessage()    {}
func (*IDs) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d2ebd3ec91d9e1b, []int{3}
}

func (m *IDs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IDs.Unmarshal(m, b)
}
func (m *IDs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IDs.Marshal(b, m, deterministic)
}
func (m *IDs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IDs.Merge(m, src)
}
func (m *IDs) XXX_Size() int {
	return xxx_messageInfo_IDs.Size(m)
}
func (m *IDs) XXX_DiscardUnknown() {
	xxx_messageInfo_IDs.DiscardUnknown(m)
}

var xxx_messageInfo_IDs proto.InternalMessageInfo

func (m *IDs) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func init() {
	proto.RegisterType((*RestrictRequest)(nil), "restricter.RestrictRequest")
	proto.RegisterType((*Restricted)(nil), "restricter.Restricted")
	proto.RegisterMapType((map[string]string)(nil), "restricter.Restricted.DataEntry")
	proto.RegisterType((*IDsRequest)(nil), "restricter.IDsRequest")
	proto.RegisterType((*IDs)(nil), "restricter.IDs")
}

func init() { proto.RegisterFile("restricter.proto", fileDescriptor_8d2ebd3ec91d9e1b) }

var fileDescriptor_8d2ebd3ec91d9e1b = []byte{
	// 247 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0x4f, 0x4b, 0xc3, 0x40,
	0x10, 0xc5, 0x9b, 0x6c, 0x95, 0x66, 0x3c, 0xb4, 0x0c, 0xa2, 0x4b, 0xbc, 0x2c, 0x7b, 0xca, 0x29,
	0x48, 0x14, 0xfc, 0x73, 0x13, 0xe2, 0xa1, 0xd7, 0xfd, 0x06, 0xab, 0x99, 0x43, 0xa9, 0x58, 0xdd,
	0xdd, 0x08, 0xc1, 0x83, 0x5f, 0x5d, 0x76, 0x4c, 0x1a, 0x95, 0xd0, 0xdb, 0x9b, 0x97, 0x97, 0x79,
	0xbf, 0x61, 0x61, 0xe5, 0xc8, 0x07, 0xb7, 0x79, 0x0e, 0xe4, 0xca, 0x37, 0xb7, 0x0b, 0x3b, 0x84,
	0xd1, 0xd1, 0x77, 0xb0, 0x34, 0xfd, 0x64, 0xe8, 0xbd, 0x25, 0x1f, 0x10, 0x61, 0xde, 0x7a, 0x72,
	0x32, 0x51, 0x49, 0x21, 0x0c, 0xeb, 0xe8, 0x6d, 0xa9, 0xf3, 0x32, 0x55, 0xa2, 0xc8, 0x0c, 0x6b,
	0xfd, 0x09, 0x30, 0xfc, 0x4a, 0x0d, 0x5e, 0xc3, 0xbc, 0xb1, 0xc1, 0xca, 0x44, 0x89, 0xe2, 0xa4,
	0x52, 0xe5, 0xaf, 0xd6, 0x31, 0x55, 0xd6, 0x36, 0xd8, 0xc7, 0xd7, 0xe0, 0x3a, 0xc3, 0xe9, 0xfc,
	0x06, 0xb2, 0xbd, 0x85, 0x2b, 0x10, 0x5b, 0xea, 0xb8, 0x37, 0x33, 0x51, 0xe2, 0x29, 0x1c, 0x7d,
	0xd8, 0x97, 0x96, 0x64, 0xca, 0xde, 0xcf, 0x70, 0x9f, 0xde, 0x26, 0xba, 0x02, 0x58, 0xd7, 0xfe,
	0x10, 0x72, 0xbf, 0x2d, 0xdd, 0x6f, 0xd3, 0xe7, 0x20, 0xd6, 0xb5, 0x8f, 0x1f, 0x36, 0x8d, 0x67,
	0x50, 0x61, 0xa2, 0xac, 0xbe, 0x60, 0x31, 0x30, 0xe2, 0x03, 0x2c, 0x06, 0x74, 0xbc, 0x98, 0xba,
	0xa2, 0xef, 0xcc, 0xcf, 0xa6, 0x4f, 0xd4, 0x33, 0xbc, 0xe4, 0x02, 0xfc, 0x13, 0x18, 0x61, 0xf3,
	0xe5, 0x3f, 0x5f, 0xcf, 0x9e, 0x8e, 0xf9, 0x61, 0xae, 0xbe, 0x03, 0x00, 0x00, 0xff, 0xff, 0x4c,
	0x76, 0x22, 0x7e, 0xac, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// RestrictClient is the client API for Restrict service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type RestrictClient interface {
	Restrict(ctx context.Context, in *RestrictRequest, opts ...grpc.CallOption) (*Restricted, error)
	Ids(ctx context.Context, in *IDsRequest, opts ...grpc.CallOption) (*IDs, error)
}

type restrictClient struct {
	cc *grpc.ClientConn
}

func NewRestrictClient(cc *grpc.ClientConn) RestrictClient {
	return &restrictClient{cc}
}

func (c *restrictClient) Restrict(ctx context.Context, in *RestrictRequest, opts ...grpc.CallOption) (*Restricted, error) {
	out := new(Restricted)
	err := c.cc.Invoke(ctx, "/restricter.Restrict/restrict", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *restrictClient) Ids(ctx context.Context, in *IDsRequest, opts ...grpc.CallOption) (*IDs, error) {
	out := new(IDs)
	err := c.cc.Invoke(ctx, "/restricter.Restrict/ids", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RestrictServer is the server API for Restrict service.
type RestrictServer interface {
	Restrict(context.Context, *RestrictRequest) (*Restricted, error)
	Ids(context.Context, *IDsRequest) (*IDs, error)
}

// UnimplementedRestrictServer can be embedded to have forward compatible implementations.
type UnimplementedRestrictServer struct {
}

func (*UnimplementedRestrictServer) Restrict(ctx context.Context, req *RestrictRequest) (*Restricted, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Restrict not implemented")
}
func (*UnimplementedRestrictServer) Ids(ctx context.Context, req *IDsRequest) (*IDs, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ids not implemented")
}

func RegisterRestrictServer(s *grpc.Server, srv RestrictServer) {
	s.RegisterService(&_Restrict_serviceDesc, srv)
}

func _Restrict_Restrict_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestrictRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestrictServer).Restrict(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restricter.Restrict/Restrict",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestrictServer).Restrict(ctx, req.(*RestrictRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Restrict_Ids_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RestrictServer).Ids(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/restricter.Restrict/Ids",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RestrictServer).Ids(ctx, req.(*IDsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Restrict_serviceDesc = grpc.ServiceDesc{
	ServiceName: "restricter.Restrict",
	HandlerType: (*RestrictServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "restrict",
			Handler:    _Restrict_Restrict_Handler,
		},
		{
			MethodName: "ids",
			Handler:    _Restrict_Ids_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "restricter.proto",
}
