-- EDIT SECTION --

-- REMOVE SECTION --
DROP TABLE deleted_t CASCADE;
DROP TRIGGER equal_meeting_id_on_agenda_item_t_content_object_id_assieb89ee8 ON agenda_item_t;
DROP TRIGGER equal_meeting_id_on_assignment_t_agenda_item_id ON assignment_t;
DROP TRIGGER equal_meeting_id_on_agenda_item_t_content_object_id_motion_id ON agenda_item_t;
DROP TRIGGER equal_meeting_id_on_motion_t_agenda_item_id ON motion_t;
DROP TRIGGER equal_meeting_id_on_assignment_candidate_t_assignment_id ON assignment_candidate_t;
DROP TRIGGER equal_meeting_id_on_assignment_t_candidate_ids ON assignment_t;
DROP TRIGGER equal_meeting_id_on_meeting_mediafile_t_attachment_ids_a02016b9 ON meeting_mediafile_t;
DROP TRIGGER equal_meeting_id_on_assignment_t_attachment_meeting_media9bbdf7 ON assignment_t;
DROP TRIGGER equal_meeting_id_on_meeting_mediafile_t_attachment_ids_a29e0815 ON gm_meeting_mediafile_attachment_ids_t;
DROP TRIGGER equal_meeting_id_on_chat_group_t_read_group_ids ON chat_group_t;
DROP TRIGGER equal_meeting_id_on_group_t_read_chat_group_ids ON group_t;
DROP TRIGGER equal_meeting_id_on_chat_group_t_read_group_ids_intermediate ON nm_chat_group_read_group_ids_group_t;

-- RENAME SECTION --

-- ADD SECTION --
