version: "3"
services:
    backend:
        build: ../..
        image: openslides-backend
        ports:
            - "9002:9002"
            - "9003:9003"
        environment:
            - DATASTORE_READER_HOST=reader
            - DATASTORE_READER_PORT=9010
            - DATASTORE_WRITER_HOST=writer
            - DATASTORE_WRITER_PORT=9011
        depends_on:
            - writer
            - reader
    reader:
        build:
            context: "https://github.com/OpenSlides/openslides-datastore-service.git"
            args:
                MODULE: "reader"
                PORT: "9010"
        image: openslides-datastore-reader
        ports:
            - "9010:9010"
        depends_on:
            - postgresql
    writer:
        build:
            context: "https://github.com/OpenSlides/openslides-datastore-service.git"
            args:
                MODULE: "writer"
                PORT: "9011"
        image: openslides-datastore-writer
        ports:
            - "9011:9011"
        depends_on:
            - postgresql
            - redis
    postgresql:
        image: postgres:11
        environment:
            - POSTGRES_USER=openslides
            - POSTGRES_PASSWORD=openslides
            - POSTGRES_DB=openslides
    redis:
        image: redis:alpine