name: Dummy

on:
  workflow_run:
    workflows: [Project automation pull request opened]
    types:
      - requested
      - in_progress
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{ toJson(github.event.action) }}"
      - run: echo "${{ toJson(github.event.workflow_run.event) }}"
      - run: echo "${{ toJson(github.event.workflow_run.pull_requests) }}"