name: Project automation for reviews
on:
  pull_request_review:
    types:
      - submitted

jobs:
  pull_request_review_submitted:
    runs-on: ubuntu-latest
    name: Pull request review submitted
    steps:
      - run: echo "Pull request review submitted, setting the status is delegated"
