name: Project automation
on:
  pull_request_review:
    types:
      - submitted

jobs:
  pull_request_approved:
    name: Pull request approved
    if: github.event.review.state == 'approved'
    uses: ./.github/workflows/project-automation.yml
    secrets: inherit
    with:
      resource_node_id: ${{ github.event.pull_request.node_id }}
      status_value: "Reviewer approved"
