name: Project automation helper
on:
  workflow_call:
    inputs:
      resource_node_id:
        required: true
        type: string
      status_value:
        required: true
        type: string

jobs:
  workflow_call:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_call'
    steps:
      - uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_app_ID: ${{ secrets.AUTOMATION_APP_ID }}
          gh_app_installation_ID: ${{ secrets.AUTOMATION_APP_INSTALLATION_ID }}
          gh_app_secret_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
          organization: OpenSlides
          project_id: 2
          resource_node_id: ${{ inputs.resource_node_id }}
          status_value: ${{ inputs.status_value }}
