name: Project automation
on:
  workflow_call:
    inputs:
      resource_node_id:
        required: true
        type: string
      status_value:
        required: true
        type: string
  issues:
    types:
      - opened
      - reopened
      - closed
  pull_request_target:
    types:
      - opened
      - reopened
      - review_requested
      - closed
  pull_request_review:
    types:
      - submitted

jobs:
  workflow_call:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_call'
    steps:
      - uses: leonsteinhaeuser/project-beta-automations@v2.1.0
        with:
          gh_app_ID: ${{ secrets.AUTOMATION_APP_ID }}
          gh_app_installation_ID: ${{ secrets.AUTOMATION_APP_INSTALLATION_ID }}
          gh_app_secret_key: ${{ secrets.AUTOMATION_APP_PRIVATE_KEY }}
          organization: OpenSlides
          project_id: 2
          resource_node_id: ${{ inputs.resource_node_id }}
          status_value: ${{ inputs.status_value }}
  issue_opened:
    if: github.event_name == 'issues' && (github.event.action == 'opened' || github.event.action == 'reopened')
    uses: ./.github/workflows/project-automation.yml
    with:
      resource_node_id: ${{ github.event.issue.node_id }}
      status_value: "Planning"
  pull_request_opened:
    if: github.event_name == 'pull_request_target' && (github.event.action == 'opened' || github.event.action == 'reopened')
    uses: ./.github/workflows/project-automation.yml
    with:
      resource_node_id: ${{ github.event.pull_request.node_id }}
      status_value: "Work in progress"
  pull_request_review_requested:
    if: github.event_name == 'pull_request_target' && github.event.action == 'review_requested'
    uses: ./.github/workflows/project-automation.yml
    with:
      resource_node_id: ${{ github.event.pull_request.node_id }}
      status_value: "Review in progress"
  pull_request_changes_requested:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'changes_requested'
    uses: ./.github/workflows/project-automation.yml
    with:
      resource_node_id: ${{ github.event.pull_request.node_id }}
      status_value: "Work in progress"
  pull_request_approved:
    if: github.event_name == 'pull_request_review' && github.event.review.state == 'approved'
    uses: ./.github/workflows/project-automation.yml
    with:
      resource_node_id: ${{ github.event.pull_request.node_id }}
      status_value: "Reviewer approved"
  pull_request_or_issue_closed:
    if: github.event.action == 'closed'
    uses: ./.github/workflows/project-automation.yml
    with:
      resource_node_id: ${{ github.event.pull_request.node_id }}
      status_value: "Done"
